### ISSUE TITLE
EasyUAE integration

### ISSUE THREAD

**Issue by samo790** [khval/e-uae-1-0-0#12]
It would be nice to investigate the possibility of integrating the EasyUAE GUI into the latest release

http://os4depot.net/?function=showfile&file=emulation/computer/e-uae.lha

**Comment by khval** [comment]
They chouse to put a AREXX port into UAE, where normally the GUI is, 
maybe there is MUI GUI for MorphOS or something.

**Comment by samo790** [comment]
I don't understand, there is no a Reaction GUI code in that source?

**Comment by khval** [comment]
Works the same way as MplayerGUI,

man. 5. des. 2022 kl. 17:31 skrev samo79 ***@***.***>:

**Comment by samo790** [comment]
There is a Reaction GUI made by Costel Mincea
Here a grab:
http://os4depot.net/filedata/snapshot/8847_1_snap.png

Mmm maybe is not present in that archive.. need to check
