### ISSUE TITLE
Add alt+enter to switch window/fullscreen

### ISSUE THREAD

**Issue by samo790** [khval/e-uae-1-0-0#13]
Kas1e added alt-enter support into his SDL based version so to switch to window mode/fullscreen and viceversa, would be cool if you can implement this feature too

Here his test binary:
http://kas1e.mikendezign.com/aos4/uae/uae_no_mcrxr.zip

**Comment by kas1e** [comment]
Yeah, that good suggestion ! It quite usable to be able to swith between windows/fullscreen by alt+enter

**Comment by khval** [comment]
the key code for emulator is "CTRL+ALT+S"

Something I leaned when working on this, there lots of keyboard code I did not know about, a lot stuff I wanted was there, but I did not know about it, same goes for mouse grab :-)

**Comment by kas1e** [comment]
What Samo mean, is to add another shortcn, so it will be not only "ctrl+alt+s", but also "alt+enter" too. It's much easer to switch by als+enter, and many software do it like this on many platforms (that why i add it before as well).

**Comment by samo790** [comment]
Yeah, as kas1e says... ctrl+alt+s is ok to be introduced if it was designed for switching win/full but ...it's not that comfortable for most users!
Maybe the good old alt+enter could be added as an alias for ?
Would be good for sure :)

**Comment by khval** [comment]
It’s supposed to not conflict with programs running in UAE.
but we have unused F11 and F12 keys, never used by Amiga programs, as well as the MENU key on the keyboard is also never used.

**Comment by kas1e** [comment]
F11 imho good. At least in Odyssey it also F11 for fullscreen.
Through with alt+enter which i added to sdl  verison there wasn't problems too. But maybe F11 will be better indeed in some cases..

**Comment by samo790** [comment]
Alt+Enter causes no conflict whatsoever in E-UAE, so it will be 100% safe to use
The use of the F11 key on the web browsers is a bit different story.. this is reminiscent of the mainstream browsers which rightly being now a consolidated standard worldwide and so it was also been introduced in the same way in Odyssey .. just like the F5 key for the page refresh
